backend:
  name: github
  repo: agustinmulet/agustinmuletblog

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: /posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: ogImage, label: ImageURL }
      - { name: description, label: OG Description }
      - { name: date, label: Created At, widget: date }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Post, widget: markdown }
