backend:
  name: github
  repo: agustinmulet/agustinmuletblog

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created At, widget: date }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Post, widget: markdown }